/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/auth/login': RouteRecordInfo<'/admin/auth/login', '/admin/auth/login', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/berita': RouteRecordInfo<'/berita', '/berita', Record<never, never>, Record<never, never>>,
    '/berita1': RouteRecordInfo<'/berita1', '/berita1', Record<never, never>, Record<never, never>>,
    '/donasi1': RouteRecordInfo<'/donasi1', '/donasi1', Record<never, never>, Record<never, never>>,
    '/info-donatur': RouteRecordInfo<'/info-donatur', '/info-donatur', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/riwayat-donasi': RouteRecordInfo<'/riwayat-donasi', '/riwayat-donasi', Record<never, never>, Record<never, never>>,
  }
}
